angular.module("lcbapp").run(["$templateCache", function($templateCache)
{
	$templateCache.put("features/faq/faq.html","
		<div id=\"afaq\" \class=\"anchor\"></div>\n
		<div id=\"faq\" class=\"row\">\n
		<img src=\"/static/images/faq/banner.png\" class=\"img-responsive\">\n
		<dl class=\"container\">\n\n<dt class=\"well\">Q1: 购买开开保车险，我能享受哪些优惠？</dt>\n<dd>\n<ol>\n<li>更优惠的价格：您可以在电网销85折的基础上折上折买车险，同时还能拿返现，如购买优选车险，参加好车主驾驶评级活动，最高可省40%。</li>\n<li>更多的服务：您除了能享受到保险公司无差别的服务外,您还能免费安装使用价值600元的OBD设备，同时享受洗车，养车和卡拉丁空调滤芯更换等服务。</li>\n</ol>\n</dd>\n\n<dt class=\"well\">Q2: 在开开保购买与在保险公司购买有何区别？</dt>\n<dd>您获得的保单都是由保险公司承保的，您可以享受到保险公司无差别的理赔及其相关服务。在开开保购买，您还可享受更优惠的价格和更多的服务。</dd>\n\n<dt class=\"well\">Q3: 现在开通的区域有哪些？</dt>\n<dd>开开保现已开通北京，上海，深圳，下一步我们会继续开通重庆，山东，天津，敬请期待。</dd>\n\n    <dt class=\"well\">Q4:现在提供哪些车险产品？</dt>\n    <dd>目前提供优选车险（参与驾驶评测，保费直降，最高可省40%），绿色车险（开或不开都有现金奖励，最高可返40%），凹凸专属车险（车辆租一天，保费省一天，最高可省100%）。后续会有按里程收费和按行驶天数收费等更多创新车险产品推出，敬请期待。</dd>\n\n    <dt class=\"well\">Q5: 如何支付保费？</dt>\n    <dd>目前支持支付宝平和微信支付，部分城市如上海支持线下支付。线上支付各种支付方式限额不一致，当支付金额大于3000元时建议您选择支付宝支付。</dd>\n\n    <dt class=\"well\">Q6:OBD盒子如何安装？</dt>\n<dd>OBD盒子会直接快递给您，部分城市我们会派专人派送。您只需按照盒子外包装上的按照流程，打开设备绑定界面，进行操作即可。</dd>\n\n    <dt class=\"well\">Q7: 如何购买优选车险？</dt>\n<dd>首先，您需要报名参加好车主驾驶评级活动，开开保会根据您三个月的驾驶行为进行评测，您可以根据评级结果直接优惠购车险，最高可省40%保费。</dd>\n\n<dt class=\"well\">Q8: 购买绿色车险，奖励如何获得？可以提现吗？</dt>\n    <dd>开开保会根据您每天的驾驶习惯为您打分给予您一定的现金奖励，您可以进入用户中心我的钱包里进行查看或者我的奖励中查看。当天的现金奖励会于第二天发放到您的账户余额中，超过50元时，您可以选择提现。</dd>\n
\n    <dt class=\"well\">Q9: 购买凹凸专属车险，租车奖励如何获得？</dt>\n<dd>租车当天的保费奖励请到您凹凸账户查看。关于养车宝洗车券和卡拉丁服务请到开开保钱包中查看并按流程提示使用。</dd>\n\n    <dt class=\"well\">Q10: 钱包里的养车宝抵用券如何使用？</dt>\n    <dd>养车宝抵用券信息包含编号，金额和有效期，您只需复制兑换码，打开养车宝APP，注册登录后即可进行服务兑换。友情提示，每一张抵用券的有效期为3个月。</dd>\n\n    <dt class=\"well\">Q11:出险后如何理赔？</dt>\n    <dd>\n<p>你可以直接拨打您所投保的保险公司电话，保险公司将会为您提供无差别的理赔及相关服务。以下报案电话可能对您会有帮助：</p>\n      <ul>\n<li>中国平安—95511</li>\n        <li>太平洋保险—95500</li>\n        <li>人保财险—95518</li>\n<li>人寿财险—95519</li>\n        <li>紫金保险—4008280018</li>\n<li>大地保险—95590</li>\n      </ul>\n    </dd>\n\n  </dl>\n</div>");
$templateCache.put("features/sdk/sdk.html","<div id=\"asdk\"
class=\"anchor\"></div>\n<div id=\"sdk-container\" class=\"row\">\n\n  <img src=\"/static/images/sdk/banner.png\" class=\"img-responsive\">\n\n  <div id=\"sdk\" class=\"container text-center\">\n    <div class=\"row\">\n      <div class=\"col-xs-6\">\n        <img src=\"/static/images/sdk/apk.png\">\n<h3>车载专用APK</h3>\n        <p>智能后视镜、智能车机、车载专版APK</p>\n<p>多尺寸、分辨率、免费定制适配</p>\n        <p>免开发、直接安装集成</p>\n      </div>\n      <div class=\"col-xs-6\">\n        <img src=\"/static/images/sdk/sdk.png\">\n<h3>OpenSDK</h3>\n        <p>智能车机、后视镜、智能硬件、移动应用、简单接入</p>\n<p>让你的应用瞬间成为UBI车险终端</p>\n      </div>\n    </div>\n    <div class=\"row\">\n<div class=\"col-xs-6\">\n<a href=\"http:/\/\/apk.kaikaibao.com.cn/kkb-v9-general-01-09.apk\" class=\"btn
btn-default\">下载测试版</a>\n        <button class=\"btn btn-default\" ng-click=\"ctrl.apply()\">申请正式版</button>\n      </div>\n      <div class=\"col-xs-6\">\n        <button class=\"btn btn-default\" ng-click=\"ctrl.apply()\">申请SDK</button>\n      </div>\n    </div>\n</div>\n\n<img src=\"/static/images/sdk/banner_dvr.png\"class=\"img-responsive\">\n\n<div id=\"dvr\" class=\"text-center\">\n    <h3>车机端App</h3>\n    <div>\n<span>\n        <img src=\"/static/images/sdk/dvr/dvr1.png\"><br/>行车收益<br/>收益抵扣保费\n      </span>\n<span>\n        <img src=\"/static/images/sdk/dvr/dvr2.png\"><br/>行程回顾<br/>一目了然\n     </span>\n<span>\n        <img src=\"/static/images/sdk/dvr/dvr3.png\"><br/>每日评分<br/>挑战自我\n      </span>\n<span>\n        <img src=\"/static/images/sdk/dvr/dvr4.png\"><br/>驾驶评级<br/>低价抵扣车险\n     </span>\n<span>\n        <img src=\"/static/images/sdk/dvr/dvr5.png\"><br/>违章查询<br/>微信定时推送\n      </span>\n
</div>\n  </div>\n\n  <div id=\"h5\" class=\"text-center\">\n<h3>手机移动端H5</h3>\n    <img src=\"/static/images/sdk/h5.png\">\n    <div class=\"container\">\n      <div class=\"row\">\n        <div class=\"col\">\n车险直接在线报价和购买，低价一目了然\n        </div>\n        <div class=\"col\">\n历史行车轨迹，随时查\n        </div>\n        <div class=\"col\">\n          驾驶评级，对应折扣车险\n</div>\n        <div class=\"col\">\n          行车评分周周评，月月发\n        </div>\n</div>\n    </div>\n  </div>\n\n</div>");
$templateCache.put("features/templates/footer.html","<a id=\"acontactus\"
class=\"anchor\"></a>\n<footer id=\"footer\">\n\n  <div class=\"container\">\n\n<div class=\"row\">\n      <div id=\"contactus\" class=\"col-xs-7\">\n<h4>联系我们</h4>\n        <p id=\"phone\">\n          <img src=\"/static/images/icons/icon_phone.png\" class=\"pull-left\">\n          <a href=\"tel:4009663899\">400-966-3899</a>\n          <span>客户热线 (工作日：9:00 -
18:00)</span>\n        </p>\n        <p><img src=\"/static/images/icons/icon_email.png\">客服邮箱：<a href=\"mailto:service@kaikaibao.com\">service@kaikaibao.com</a></p>\n<p><img src=\"/static/images/icons/icon_email.png\">商务合作：<a href=\"mailto:bd@kaikaibao.com\">bd@kaikaibao.com</a></p>\n<p>地址：上海市江场三路238号717室</p>\n      </div>\n      <div class=\"col-xs-5\">\n<div class=\"row\">\n          <div class=\"col-xs-6\">\n<h4>关注我们</h4>\n            <p class=\"text-nowrap\">微信公众号：“开开保”<br/>（针对全国用户）</p>\n            <img src=\"/static/images/qrcode_wechat.png\">\n          </div>\n          <div class=\"col-xs-6\">\n            <h4>下载App</h4>\n            <p class=\"text-nowrap\">移动客户端：开开保<br/>（iOS/Android）</p>\n            <img src=\"/static/images/qrcode_app.png\">\n          </div>\n        </div>\n</div>\n    </div>\n\n  </div>\n\n  <div id=\"copyright\" class=\"container text-center\">\n    版权所有©上海弘西有限公司 2015-2016 | 沪ICP备15024067号-2\n
</div>\n\n</footer>\n");
$templateCache.put("features/templates/header.html","<!-- Fixed navbar -->\n<nav class=\"navbar lcb-navbar-top navbar-fixed-top\">\n  <div class=\"container\">\n<div class=\"navbar-header\">\n      <button type=\"button\" class=\"navbar-toggle collapsed\" data-toggle=\"collapse\" data-target=\"#navbar\" aria-expanded=\"false\" aria-controls=\"navbar\">\n        <span class=\"sr-only\">Toggle navigation</span>\n        <span class=\"icon-bar\"></span>\n<span class=\"icon-bar\"></span>\n        <span class=\"icon-bar\"></span>\n</button>\n      <a class=\"navbar-brand\" href=\"#\"><img src=\"/static/images/logo.png\"></a>\n    </div>\n    <div id=\"navbar\" class=\"navbar-collapse collapse\">\n      <ul class=\"nav navbar-nav navbar-right\">\n        <li><a ui-sref=\"welcome\">首页</a></li>\n        <li><a ui-sref=\"welcome({\'#\': \'aubi\'})\">UBI车险</a></li>\n        <li><a ui-sref=\"welcome({\'#\': \'agrade\'})\">评级系统</a></li>\n        <li><a ui-sref=\"sdk({\'#\': \'asdk\'})\">开放平台</a></li>\n        <li><a ui-sref=\"faq({\'#\': \'afaq\'})\">常见问题</a></li>\n        <li><a href=\"#acontactus\" target=\"_self\">联系我们</a></li>\n      </ul>\n    </div
><!--/.nav-collapse -->\n  </div>\n</nav>\n\n<script>\n
$(document).ready(function(){\n    $(window).scroll(function() { // check if
scroll event happened\n      if ($(document).scrollTop() > 0) { // check if user
scrolled more than 50 from top of the browser window\n        $(\".navbar-fixed-top\").removeClass(\'lcb-navbar-top\');\n        $(\".navbar-fixed-top\").addClass(\'navbar-inverse\');\n      } else {\n        $(\".navbar-fixed-top\").removeClass(\'navbar-inverse\');\n        $(\".navbar-fixed-top\").addClass(\'lcb-navbar-top\');\n      }\n    });\n});\n$(document).on(\'click\',\'.navbar-collapse.in\',function(e) {\n    if($(e.target).is(\'a\') ) {\n      $(this).collapse(\'hide\');\n    }\n});\n</script>"); $templateCache.put("features/welcome/carousel.html","<div id=\"carousel\" class=\"row\">\n  <div uib-carousel active=\"0\"
interval=\"5000\">\n    <div uib-slide index=\"0\">\n      <img src=\"/static/images/welcome/slide1.png\" class=\"img-responsive\">\n</div>\n    <!--div uib-slide index=\"1\">\n<img src=\"/static/images/welcome/slide1.png\" class=\"img-responsive\">\n</div>\n    <div uib-slide index=\"2\">\n      <img src=\"/static/images/welcome/slide1.png\" class=\"img-responsive\">\n</div>\n    <div uib-slide index=\"3\">\n      <img src=\"/static/images/welcome/slide1.png\" class=\"img-responsive\">\n </div-->\n  </div>\n</div>");
$templateCache.put("features/welcome/grade.html","<a id=\"agrade\"
class=\"anchor\"></a>\n<div id=\"grade\">\n  <h3 class=\"text-center\">驾驶评级系统</h3>\n  <div uib-carousel active=\"0\" interval=\"5000\">\n<div uib-slide index=\"0\">\n      <img src=\"/static/images/welcome/grade/habit.png\" class=\"pull-left\">\n<div>\n        <h4>驾驶习惯</h4>\n<p>文明驾驶，减少急加速、急减速、急转弯的次数，不开赌气车，少做危险的变道行为，有助于降低危险系数</p>\n      </div>\n</div>\n    <div uib-slide index=\"1\">\n      <img src=\"/static/images/welcome/grade/milage.png\" class=\"pull-left\">\n<div>\n        <h4>驾驶里程</h4>\n<p>少开车，尤其是减少拥堵时间的用车，增加绿色出行比例，可以提升评级分数</p>\n      </div>\n    </div>\n    <div uib-slide index=\"2\">\n      <img src=\"/static/images/welcome/grade/duration.png\" class=\"pull-left\">\n<div>\n        <h4>驾驶时间</h4>\n        <p>避开高峰期出行，减少夜间驾驶，避免疲劳驾驶，可以有效提升安全指数</p>\n</div>\n    </div>\n    <div uib-slide index=\"3\">\n      <img
src=\"/static/images/welcome/grade/road.png\" class=\"pull-left\">\n<div>\n        <h4>驾驶路线</h4>\n        <p>避开拥堵路段，尽量在熟悉的路段上行驶，有助于提升驾驶评级</p>\n</div>\n    </div>\n    <div uib-slide index=\"4\">\n      <img src=\"/static/images/welcome/grade/id.png\" class=\"pull-left\">\n      <div>\n<h4>身份特质</h4>\n        <p>资料是否完善，年龄、驾龄、家庭、信用等因素，也将影响安全指数</p>\n      </div>\n</div>\n  </div>\n</div>");
$templateCache.put("features/welcome/partner.html","<div id=\"partner\"
class=\"row text-center\">\n  <h3>合作伙伴</h3>\n  <div uib-carousel active=\"0\"
interval=\"0\">\n    <div uib-slide index=\"0\">\n      <img src=\"/static/images/welcome/partner/pingan0.png\"><img src=\"/static/images/welcome/partner/cpic0.png\"><img src=\"/static/images/welcome/partner/clpc0.png\"><img src=\"/static/images/welcome/partner/axa0.png\">\n    </div>\n    <div uib-slide index=\"1\">\n      <img src=\"/static/images/welcome/partner/picc0.png\"><img src=\"/static/images/welcome/partner/zking0.png\"><img src=\"/static/images/welcome/partner/continent0.png\"><img src=\"/static/images/welcome/partner/yangchebao0.png\">\n    </div>\n</div>\n</div>\n\n<div class=\"hidden\">\n  <img src=\"/static/images/welcome/partner/pingan1.png\"><img src=\"/static/images/welcome/partner/cpic1.png\"><img src=\"/static/images/welcome/partner/clpc1.png\"><img src=\"/static/images/welcome/partner/axa1.png\">\n  <img src=\"/static/images/welcome/partner/picc1.png\"><img src=\"/static/images/welcome/partner/zking1.png\"><img src=\"/static/images/welcome/partner/continent1.png\"><img
src=\"/static/images/welcome/partner/yangchebao1.png\">\n</div>\n");
$templateCache.put("features/welcome/welcome.html","<div id=\"welcome\">\n\n<ng-include src=\"\'features/welcome/carousel.html\'\"></ng-include>\n\n  <a id=\"aubi\" class=\"anchor\"></a>\n  <div id=\"ubi\" class=\"text-center\">\n<h3>开开保UBI车险</h3>\n    <div class=\"row\">\n      <div class=\"col-xs-4\">\n<img src=\"/static/images/welcome/ubi/model.png\"><br/>车型\n      </div>\n<div class=\"col-xs-4\">\n        <img src=\"/static/images/welcome/ubi/age.png\"><br/>车龄\n      </div>\n      <div class=\"col-xs-4\">\n        <img src=\"/static/images/welcome/ubi/insurance.png\"><br/>出险\n      </div>\n</div>\n    <div class=\"row\">\n      <div class=\"col-xs-4\">\n        <img
src=\"/static/images/welcome/ubi/rules.png\"><br/>违章\n      </div>\n      <div class=\"col-xs-4\">\n        <img src=\"/static/images/welcome/ubi/habit.png\"><br/>用车习惯\n      </div>\n    <div class=\"col-xs-4\">\n        <img src=\"/static/images/welcome/ubi/usage.png\"><br/>车险用量\n      </div>\n</div>\n  </div>\n\n  <!--div id=\"buy\" class=\"row text-center\">\n<h2>直接底价购买</h2>\n    实付 = 保险公司出单价格 - 开开保UBI优惠（最高40%）\n  </div-->\n\n  <div id=\"product\" class=\"container text-center\">\n    <div class=\"row\">\n<div class=\"col-xs-6\">\n        <img src=\"/static/images/welcome/product/hunt.png\">\n        <h3>优选车险</h3>\n<p>直接打折购买</p>\n        <p>少些套路，多些真诚</p>\n        <p>专为洒脱直率的车主准备！</p>\n</div>\n      <div class=\"col-xs-6\">\n        <img
src=\"/static/images/welcome/product/hx.png\">\n        <h3>惠选车险</h3>\n<p>行车优收益，收益抵保益</p>\n        <p>特别适合精打细算的车主</p>\n      </div>\n   </div>\n</div>\n\n  <ng-include src=\"\'features/welcome/grade.html\'\"></ng-include>\n\n  <lcb-partner></lcb-partner>\n\n</div>");}]);
